### ISSUE TITLE
gymnasium environment에서 maze game 구현

### ISSUE THREAD

**Issue by chointer** [chointer/maze#2]
### ISSUE
- Type: `feature`
- Detail: 미로 게임을 gymnasium 환경에서 구현
</br>

### TODO
- [x] `__init__`. 변수 구성 및 초기화
- [x] observation 구현
- [x] `reset`. Reset 구현
- [x] `step`. Step 구현
- [x] `render`. Rendering 구현
- [x] `close`. Close 구현
- [x] manual control 구현
- [x] 환경을 gymnasium에 등록하기 (`register`)
- [x] python package로 구조화
</br>

### Reference
- Gymnasium Document, Make your own custom environment. https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/
